version: "3.7"
services:
  sunday-proxy:
    image: jwilder/nginx-proxy
    container_name: sunday-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./docker-compose/nginx:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-compose/nginx/vhosts:/etc/nginx/vhost.d
      - ./:/usr/share/nginx/html
    networks:
      - sunday
    depends_on:
      - nginx
  ssl-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-companion
    volumes:
      - ./docker-compose/nginx:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - sunday-proxy
    depends_on:
      - sunday-proxy
  nginx:
    image: nginx:alpine
    container_name: sunday-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/vhosts:/etc/nginx/conf.d/
      - ./:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=${VIRTUAL_APP_HOST}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${VIRTUAL_APP_HOST}
      - LETSENCRYPT_EMAIL=jesusant.guerrero@gmail.com
    networks:
      - sunday
  web:
    build:
      args:
        user: 'sunday'
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: Dockerfile
    image: sunday
    container_name: sunday-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www
      - ./docker-compose/web/timezone:/etc/timezone
      - ./docker-compose/web/cron/scheduler-cron:/etc/cron.d/scheduler-cron
      - sunday_db:/var/lib/mysql
    networks:
      - sunday
  db:
    image: mysql:5.7
    container_name: sunday-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - sunday_db:/var/lib/mysql
      - ./docker-compose/mysql:/home/root/cache/
    networks:
      - sunday
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - ./docker-compose/redis:/data
    networks:
      - sunday
  cron:
    build:
      context: .
      dockerfile: cron.dockerfile
    container_name: cron
    volumes:
      - ./:/var/www
    networks:
      - sunday
networks:
  sunday:
    driver: bridge
volumes:
  sunday_db:
    driver: local
